name: 'Setup Test Environment'
description: 'Setup Minikube and build the project'
inputs:
   minikube-version:
      description: 'Minikube version to install'
      required: false
      default: '1.33.0'
   kubernetes-version:
      description: 'Kubernetes version to use'
      required: false
      default: '1.29.1'
   driver:
      description: 'Minikube driver to use'
      required: false
      default: 'docker'
   pr-base-ref:
      description: 'PR base reference for conditional build'
      required: false
      default: ''
runs:
   using: 'composite'
   steps:
      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest
        with:
           minikube-version: ${{ inputs.minikube-version }}
           kubernetes-version: ${{ inputs.kubernetes-version }}
           driver: ${{ inputs.driver }}

      - name: npm install and build
        shell: bash
        run: |
           echo ${{ inputs.pr-base-ref }}
           if [[ "${{ inputs.pr-base-ref }}" != releases/* ]]; then
             npm install
             npm run build
           fi
