name: "Trigger Integration tests"
on:
  push:
    branches:
      - master
      - "releases/*"
  pull_request_target:
    types: [labeled, opened]
    branches:
      - master
      - "releases/*"

jobs:
  aks-integration-tests:
    name: K8S Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v1
        id: setup-kubectl
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}" # Azure credentials
          resource-group: davidgamero-ghactions-test
          cluster-name: davidgamero-ghactions-test
        id: setcontext
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          path: k8s-create-secret
          ref: davidgamero/k8-client-refactor
      - run: |
          cd k8s-create-secret
          npm install
          npm run build
      - uses: ./k8s-create-secret
        id: call-create-secret
        with:
          secret-name: integration-test-secret
          secret-type: generic
          string-data: '{ "testKey": "testValue" }'
  trigger-integration-tests:
    name: Trigger Integration tests
    if: startsWith(github.event.pull_request.head.label, format('{0}:',github.repository_owner)) || contains(github.event.pull_request.labels.*.name, 'run-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          path: IntegrationTests

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "##[set-output name=branchname;]$(echo ${GITHUB_REF##*/})"

      - name: Trigger Test run
        if: |
          github.event.pull_request.base.ref == 'releases/v1' || steps.extract_branch.outputs.branchname == 'releases/v1' || 
          github.event.pull_request.base.ref == 'master' || steps.extract_branch.outputs.branchname == 'master'
        env:
          token: ${{ secrets.L2_REPO_TOKEN }}
          commit: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.repository }}
          prnumber: ${{ github.event.pull_request.number }}
          prsource: ${{ github.event.pull_request.head.ref }}
          prtarget: ${{ github.event.pull_request.base.ref }}
          username: ${{ secrets.L2_REPO_USER }}
          prsourcerepository: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          bash ./IntegrationTests/.github/workflows/TriggerIntegrationTests.sh $token $commit $repository $prnumber $prsource $prtarget $username $prsourcerepository
